### PR TITLE
Issue 23  update arduino file and android app to new broker connection

### PR DESCRIPTION
**Pull request by Quinstedt**
The arduino files has been improved and updated.
* Added a new structure
* Created new topics 
* Added the set up for the accelerations buttons that will come in the future. 
* New values for the executions of the car movement 

Android app:
* The name of the app has been changed
* Creation of enum class and a movement connection class to avoid redudancy in the implementation of the joystick
* New topics has been created 
* The controlPad class has been updated to work with the new structure 

Related issue: #23

### CODE REVIEW

**Review by faisal1201 — APPROVED** [review]
Approval Granted.
Tasks for Issue 23 completed.

**Review by faisal1201 — DISMISSED** [review]
Approved!
Tasks for Issue 23 completed

**Review by faisal1201 — APPROVED** [review]
Approved

**Comment by platisd** [comment]
Why are you mentioning the issue in the title as `issue 23` instead of the standard and traceable way, ie #23?

**Comment by Quinstedt** [comment]
I did use  #23 in the first push comment and the pull request is also connected to the issue.

When I created the branch to an issue, GitHub suggested that name to the issue branch so I tried it out. 

Skickat från min iPhone

**Comment by platisd** [comment]
You can call the branch something that implies the issue since there's no other way to refer to it there, but in a pull request there are standardized ways of doing so (ie referring to issues) instead.

**Comment by Quinstedt** [comment]
thank you for the feedback but Im wondering if I understand you right. 
We need to refer the issue in three parts then? because know I have use it (1) in the  comment and also (2) in the right column of the pull request. But I should also use it in the pull request name? So it need to be mentioned in three parts.

**Comment by platisd** [comment]
You **must** to have the issue (1) linked to the pull request (i.e. "in the right column") and (2) it's really good if you can refer to it in the description of the pull request as long as the issue should be **closed** after the pull request is merged.

Regarding referring to it in the title of the pull request, I'd say that's the least important and I personally wouldn't do it, but if you want to, make sure you do it right and add the `#` before the number of the issue.

**Pull request merged**
