### PR TITLE
Revert "Build godot project on CI"

### PR DESCRIPTION
**Pull request by Dreia**
Reverts DIT113-V22/group-08#63 Looks like some checks did not pass after all because of a path error.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by RuthgerD** [comment]
Why?

**Comment by RuthgerD** [comment]
Seems like the last change you pushed to the previous PR about this broke it again, presumably due to the path change ?

**Comment by Dreia** [comment]
Yes it was the path

**Comment by Dreia** [comment]
This merge closes related issue #60

**Pull request merged**
