### PR TITLE
Finish Line Detection working

### PR DESCRIPTION
**Pull request by Dreia**
Created a finish line car that detects the car passing with the help of a SR04 sensor. It starts scanning for cars after 1 minute of race and stops as soon as one car has been detected at less than 2 meters distance, at which time it publishes to MQTT the time measurement in milliseconds. 
As usual find instructions [here](https://github.com/DIT113-V22/group-08/wiki/Modding-Instructions) for how to use and test.
Closes related issue #27 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Review by Quinstedt — CHANGES_REQUESTED** [review]
image

Remove the extra android app that you have in the branch.

**Comment by Quinstedt** [comment]
Some question: 
1. Is it possible to make the small bridge in the midle of the Island a little bigger, to get the car there is a real challenge. But maybe that is what you were aiming for?
image

2. Secondly, is it possible to  the hill here a little more flat? or to put some sign or text in the grown to slow down there so that players can now that? .
image
If I drive faster than 40, the car rolls and it end up up and down, and we need to restart the race.

**Comment by Dreia** [comment]
Hey @Quinstedt I can do the modifications you asked for but they have nothing to do with the finish line in itself I thin kyou were happy about that one :) I will update the model in its respective issue.

**Comment by Dreia** [comment]
Other than that I updated from master before pushing and it looks like there are some issues with the Android CI and many conflicts. Please advise.

**Comment by Dreia** [comment]
¨Go to MainActivityTest in the Android App and uncommit @test 
Run test manually. Add a picture of the test result in the comments. 
Comment @test again to avoid future problems with the CI¨  
Can anyone explain this in human language please ?

**Comment by Quinstedt** [comment]
> ¨Go to MainActivityTest in the Android App and uncommit @test Run test manually. Add a picture of the test result in the comments. Comment @test again to avoid future problems with the CI¨ Can anyone explain this in human language please ?

- Open the app in android.
- Go to AndroidTest
- Go to MainActivityTest
- Go to the last test which has the yellow tag "@LargeTest and a commenteted //@Test 
 FROM : 

image

 TO : 
image

Press the green arrow in line 94. The test will start so wait. Send a picture of the result.

Like this: 
image

Make sure that the @Test is commented before you push otherwise the CI is going to bug. 
The @LargeTest makes sure that CI ignores that test.

**Comment by restless-learner** [comment]
> ¨Go to MainActivityTest in the Android App and uncommit @test Run test manually. Add a picture of the test result in the comments. Comment @test again to avoid future problems with the CI¨ Can anyone explain this in human language please ?

Go to MainActivityTest class uncomment "//@test" where you see it is commented, run a test, after the test has passed comment "@test"  again (if I am not mistaken there only one test commented "fun test_process_of_entering_a_playerName()")  send a screenshot.

**Comment by Quinstedt** [comment]
> Hey @Quinstedt I can do the modifications you asked for but they have nothing to do with the finish line in itself I think you were happy about that one :) I will update the model in its respective issue.

@Dreia awesome. I can cannott merge will there is the conflicts tho. Do you want me to fix them sence all are related to the app?

**Comment by Dreia** [comment]
For the finish line to work, in the beginning after you compile the sketches, press reset button in the finish line panel on the left in SMCE. This puts the model in the right position so the detection can work.
Looks like there is a bug in the emulator it messes the initial position a bit.
Please let me know if the roller coasters work well, I am not that good a driver to test them :)

**Comment by Dreia** [comment]
@Quinstedt the problem of the car flipping at higher speed might have been solved as well. I didn't have the version of the app with speedometer to test but I tried to address it.

**Comment by Quinstedt** [comment]
ok . Im trying different options for the acceleration button and the joystick direction. So I will try them out in that enviroment.

**Comment by Dreia** [comment]
I forgot to add that it is now possible to get inside all the caves :)

**Review by Quinstedt — APPROVED** [review]

**Review by Quinstedt — APPROVED** [review]
image

The finish line is working and meets the acceptance criteria. The mod has been tested with different cars and it is working accordenly to the spectations.

**Pull request merged**
