### PR TITLE
Adding speed controllers

### PR DESCRIPTION
**Pull request by Quinstedt**
The camera stream have been replaced with an speedometer UI connected to the speed buttons due the lagging while recording. 
The speedometer UI is syncronised with the speed buttons, the speedomater speed is from 0 -100 increasing by 10 as the car speed. 
3 extra button have been implemented, the accelaration button, break and full speed ( we already have a stop button). 
The arduino file has been updated. 

The joystick have been reconstructed with more directions and the controlPad has a new functionality ( on realease the car continues forward). 

Comments have been added to all the methods for better understanding of the new structure of the controllers. 

In the app: 
A Static Topic class has been implented which is nested inside the BrokerConnection. 
The Splash animation has been uptaded to avoid the lag in the animation while moving to the MainActivity. 
While merging the added components to the layout have been assigned a better position according to the speedometer UI. 

Cleaned redudant code after the merge with the timer
 
Closes related issue: #62 
Closes related issue: #41 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by faisal1201** [comment]
@Quinstedt  Acceptance Criteria to the linked issues are met. The buttons function as they are suppose  and the speedometer reflects the changes in speed both in control pad and Joystick.

These are some of the issues I faced which are optional to fix :
1) When a player starts the race ,he needs to first press the Accelerate or full speed button to move the car. Just dragging the joystick or pressing the control pad buttons won't work unlike previously, But, we can include this information in the Instruction screen so the player knows how to get the car moving.
2) Pressing the brake button many times takes me back to the control choice screen. I don't think it's a problem because in a real situation a player wouldn't press the brake button that many times.

Overall, the acceptance criteria is met and some improvements are made in some classes and the Intro-animation.
Good Job ! Is there a possible reason for the above issues and can be fixed, otherwise we can approve this pull request.

**Comment by faisal1201** [comment]
Also, I am not sure about the last DOD criteria

**Comment by Quinstedt** [comment]
> @Quinstedt  Acceptance Criteria to the linked issues are met. The buttons function as they are suppose  and the speedometer reflects the changes in speed both in control pad and Joystick.
> 
> 
> 
> These are some of the issues I faced which are optional to fix :
> 
> 1) When a player starts the race ,he needs to first press the Accelerate or full speed button to move the car. Just dragging the joystick or pressing the control pad buttons won't work unlike previously, But, we can include this information in the Instruction screen so the player knows how to get the car moving.
> 
> 2) Pressing the brake button many times takes me back to the control choice screen. I don't think it's a problem because in a real situation a player wouldn't press the brake button that many times.
> 
> 
> 
> Overall, the acceptance criteria is met and some improvements are made in some classes and the Intro-animation.
> 
> Good Job ! 
> 
> Is there a possible reason for the above issues and can be fixed  ? Otherwise, we can approve this pull request.

I will fix this issues and resubmit it. I have a solution for the brake. 

I will add a base speed for the car, maybe 10 so if you press forward it will go move with 10.

**Comment by Dreia** [comment]
I will repeat here the comments I shared in Discord. It would be nice to have the car moving forward as the default case in the switch statement. The movements should move more suavely when pressing right or left. This can be done either by dividing the angle argument with a constant, or setting a rule, such as: when the player presses once the car moves X degrees...With this fixes the car might get stuck seriously less, but for when it does I suggest switching into a "debug" mode if that is not hard to implement.
Other than that, I couldn't really test the speedometer because I don't see it. For me it looks like the previous version.
Screen Shot 2022-05-21 at 17 47 28

**Comment by faisal1201** [comment]
@Dreia make sure you are in the  "Adding-Speed-Controllers" branch and it's updated. I think you might be on a different branch which doesn't have the implementations for speedometer.

**Comment by Dreia** [comment]
> @Dreia make sure you are in the "Adding-Speed-Controllers" branch and it's updated. I think you might be on a different branch which doesn't have the implementations for speedometer.

I did pull the last version but I have a Mac and maybe it's different.

**Comment by Quinstedt** [comment]
image

the test is passing manually

**Review by itsdanesh — APPROVED** [review]
I looked into the codes and I think it fulfills the pull request description. Therefore i merge this branch with the master.

Closes related issue: https://github.com/DIT113-V22/group-08/issues/62
Closes related issue: https://github.com/DIT113-V22/group-08/issues/41

**Pull request merged**
