### PR TITLE
Leaderboard UX

### PR DESCRIPTION
**Pull request by itsdanesh**
removed the extra android file

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by restless-learner** [comment]
Reviewed

**Comment by itsdanesh** [comment]
I have closed this pull request several times by mistake thinking i am adding #Close tag but instead i have closed the pull request.

**Comment by restless-learner** [comment]
Reviewed.

**Review by restless-learner — APPROVED** [review]

**Comment by Quinstedt** [comment]
I will not have merge it yet or least without  leaving a comment on what it is missing. 
@restless-learner  The pull request is not satisfying the requirements for the DoD that you have checked. 
Still missing requirements for the pull request: 
-  Missing valuable describtion
-  There is no related issue in the describtion  or specifyinf which is issue is close
-  There no explanation on why the acceptance criteria has no been meet or which issue it is going to be move to. 
- The title of the pull request is in a grey area 

One thing is what we do in the commit and another thing is  how we work with the pull request. @itsdanesh

**Comment by faisal1201** [comment]
@itsdanesh the improvements for the feedback I gave aren't implemented yet. The leaderboard was supposed to have placeholders instead of dummy names and scores. Also, I think the leaderboard screen should have a consistent background similar to the other screens. This strengthens the visual framework of our app.

**Pull request merged**
