### PR TITLE
Exploration Mode and Race Mode

### PR DESCRIPTION
**Pull request by Dreia**
This exploration mode will be uploaded as a separate mod with a few enhancements, being able to disappear and appear in another point on the map and having more freedom to explore caves and islands.
Fixes related issue: #39, #73

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by Dreia** [comment]
I finally managed to fix the camera grey cutting planes. This will work beautifully when the car climbs to the mountain to se the scenery.

**Comment by Dreia** [comment]
This is the final version of Race Mode, let me know if the clouds are ok. they are meant to guide the player towards safer routes.

**Comment by Dreia** [comment]
Encountered a few issues with forking SMCE in order to finish the exploration mod and I am hoping to resolve them this morning
Related issue: #39

**Comment by Dreia** [comment]
Added an animation for the plane that will be in Race Mode as well in order to guide the player towards finishing the game, but also making the game more engaging 
Related issue: #39, #73
For downloading the Island.zip you need to find the artifact created by the CI:
- go to Actions and select build-island.zip
- tick the three dots button on the right
- select Summary on the left menu
- go to Artifacts option in the top bar.
- The plan is to improve the CI to attach this artifact to the release of the app in the Releases wiki page

**Review by faisal1201 — COMMENTED** [review]
@Dreia  I downloaded the Island.zip file from artifacts as you instructed and pasted it inside %APPDATA%\Godot\app_userdata\SMCE\mods (PC). But, i don't get the option to switch to isle environment anymore. Am I doing anything wrong?
image

**Comment by faisal1201** [comment]
There is only one Island.pck file inside the zip file i downloaded from the artifacts . Shouldn't there be more files?
image

**Comment by RuthgerD** [comment]
the pck needs to be in the toplevel of the mods folder, i.e:
`mods > island.pck`

**Comment by faisal1201** [comment]
@Dreia I can change the mod environment now . But, instead of putting the Island.zip file in the %APPDATA%\Godot\app_userdata\SMCE\mods ,I extracted the zip file and put the .pck file inside the directory as Ruthger pointed out. You might also need to update wiki.

**Review by faisal1201 — COMMENTED** [review]
@Dreia  can you update your user story #39 .As of now, I don't see that the acceptance criteria has been met. There wasn't any elevator in the mod. If you are planning to not have it ,then remember to update the acceptance criteria in the issue. 
Acceptance criteria for #73 has been met.

**Comment by Dreia** [comment]
The last version of the island.zip is [here](https://github.com/DIT113-V22/group-08/actions/runs/2396604654) Go to artifacts and download

> @Dreia I can change the mod environment now . But, instead of putting the Island.zip file in the %APPDATA%\Godot\app_userdata\SMCE\mods ,I extracted the zip file and put the .pck file inside the directory as Ruthger pointed out. You might also need to update wiki page on modding instructions

Yes, .pck and .zip files are interchangeable. I thought it would be easier for you to just put the file in that folder, personally I made a shortcut for the mods folder and I can change the files very fast like that. It's just easier I think.

**Comment by Dreia** [comment]
The last version of the island.zip is [here](https://github.com/DIT113-V22/group-08/actions/runs/2396604654) Go to artifacts and download.
References related issue: #39, #73

**Comment by Dreia** [comment]
I have added the exploration mod as I have it now. It´s called _Exploration/Exploration_ and you can just get the normal zip file in the _Exploration folder_ 
You can have it in the same folder with the _Island.pck_ but you need a different profile to run it (make a new profile). 
I kept the finish line for the moment but I can of course delete.
I will keep the user stories open for now cause I think I will have the elevator working by tomorrow.
Related issues: #39, #73.

**Comment by Dreia** [comment]
I forgot to say that if the exploration mod doesn't work for you you might need to install the SMCE-Godot release that I made from [here] (https://github.com/DIT113-V22/smce-gd-group-08/actions/runs/2400632985#artifacts). I don't think you will need it but if you do it only takes a minute to install and it works as an update to the official version so everything we have done so far is supported.

**Comment by faisal1201** [comment]
I think you need to change the spawn location of the car in explorer mode because the current spawn location is on the sea where you can't actually drive. 
image

**Comment by faisal1201** [comment]
if you think the elevator is going to take some more time, then we can also discard it. You can just change the acceptance criteria of issue #39

**Comment by Dreia** [comment]
> I think you need to change the spawn location of the car in explorer mode because the current spawn location is on the sea where you can't actually drive.
> image

You can actually drive on the sea. Enjoy!

**Comment by faisal1201** [comment]
Alright, I'll try driving on the Sea

**Comment by Dreia** [comment]
I fixed the artifact problem. Now you can simply download the _.pck_ [here](https://github.com/DIT113-V22/group-08/actions/runs/2401723583#artifacts). I'll update the modding instructions as well

**Comment by Dreia** [comment]
Now the CI produces the two _.pck_ files and you can find them in the Actions tab (updated constantly) or in the releases page (not updated unless someone creates a new release).
Related issues: #73, #74

**Review by Quinstedt — APPROVED** [review]
The acceptance criteria of issue #39  has been deleted, tho the problems encountered with the elevator. 
The mood is working. It has been tested manually

**Pull request merged**
