### PR TITLE
added the leaderboards and updated README

### PR DESCRIPTION
**Pull request by itsdanesh**
I have added the UX for two leaderboards, added a badge for the gameServer-build and linked modding instruction from wiki to README

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by faisal1201 — COMMENTED** [review]
The buttons are working and the Leaderboard screen can be seen. The screens are not swipeable which will be implemented during Sprint 3 + Improvements.
To approve it to be merged, I would like you to fix the merge conflicts in android manifest.
And maybe  have placeholders instead of dummy data in the leaderboard.

**Comment by faisal1201** [comment]
Also, the pull request could be more descriptive. The description should mention the specific issue using the closes keyword.
For some reason, I can't see the DOD criteria.

**Comment by Quinstedt** [comment]
> The buttons are working and the Leaderboard screen can be seen. The screens are not swipeable which will be implemented during Sprint 3 . To approve it to be merged, I would like you to fix the merge conflicts in android manifest. And maybe have placeholders instead of dummy data in the leaderboard.

I think the problems is that the branch has conflicts with the main which need to be resolved before we can merge it. 
In this case is that the manifest was changed with the introduction of the splash animation. Which is the one that we need to keep.

**Comment by Quinstedt** [comment]
> The buttons are working and the Leaderboard screen can be seen. The screens are not swipeable which will be implemented during Sprint 3 . To approve it to be merged, I would like you to fix the merge conflicts in android manifest. And maybe have placeholders instead of dummy data in the leaderboard.

I wil also say that you  should also add that explanation in the commit comment above. the explanation regarding the acceptance criteria of the swipe will be implemented later.

**Comment by Quinstedt** [comment]
I have resolve the conflicts of this branch that were related because there are related to the manifest. I also renamed the class control_choice to ControlChoice to avoid problems in case the JoystickBranch is merge with the master before this one, which will lead to new conflicts to resolve. 

@faisal1201  the reason for why you couldn't see the DOD criteria was that the branch had conflicts with the master branch. 
Now that they are resolved we can see them again. 

But @itsdanesh the feedback provided from @faisal1201 and I remains. 

- [x] Maybe have placeholders instead of dummy data in the leaderboard
- [x] The description should mention the specific issue using the closes keyword and include 
       the explanation regarding the acceptance criteria of the swipe will be implemented later.

**Comment by faisal1201** [comment]
@Quinstedt  I still can't see the DoD criteria even after the conflicts are resolved.

**Comment by Quinstedt** [comment]
@faisal1201 I have added it here aswell now.

**Comment by itsdanesh** [comment]
@faisal1201 @Quinstedt I was thinking the same at the beggining but for some unknow reason it did not work. I ended up using cardView which have similar methods as Placeholder

**Comment by Quinstedt** [comment]
@itsdanesh I will fix your conflicts but you should make sure that you dont have conflicts, you avoid this by using pull in git. 
The conflicts are created because you branch is behind, you try to merge your branch with the master before pushing. 
If you dont know how to solve your conflict tag me or someone to get help.

**Review by Quinstedt — CHANGES_REQUESTED** [review]
I have review the code and test the leaderboard manually and the UX is working. 
I will say that the pull request still dont have a valuable description and it doest not have a related issue tagged.  

This request will be aprove tomorrow even tho the criteria is not meet

**Comment by Quinstedt** [comment]
Honestly I have no Idea how that ended there. How do I delete a subModule?

**Comment by platisd** [comment]
Strange then that it was somehow added. Try [these](https://stackoverflow.com/a/1260982) instructions.

**Comment by Quinstedt** [comment]
@itsdanesh Maybe you can answer Dimitrios question regarding the submodule?
image

But from what Im reading online there is something that we shouldnt use

**Comment by itsdanesh** [comment]
I am closing this pull request to fix the branch and will try to make pull request again.

**Comment by Quinstedt** [comment]
Did you try Dimitrios link on how to delete the subModule from git before closing this pull request?

**Pull request closed without merging**
