### PR TITLE
Godot publishing to MQTT

### LINKED ISSUE #27: Finish Line Detection
As a player I would like the game to end as soon as I have reached the finish line and I would like my result to be displayed in order to know how well I did.
Acceptance criteria:
- The car control is blocked within 3 seconds from crossing the finish line.
- The result is displayed on the app screen in a legible manner within 0.5 seconds after the car control has been taken away.
- The time measurement is accurate by 0.01 seconds.

To Do: 
- Mod a vehicle in the shape of the finish line and give it an infrared sensor.
- Create a "finish line" spawn location in Godot.
- Write an Arduino sketch to publish a topic to MQTT when the race has ended

### PR DESCRIPTION
**Pull request by Dreia**
Added Finish Line, Collision Detection, MQTT Godot connection, Vehicle Mod Fixes #27
I would like some help debugging _Mod/gd/mqtt.gd_  and _Mod/gd/Playground.gd_  and _Mod/gd/FinishLine.gd
The MQTT connection doesn't work, I get this error from the emulator:
```
Loaded mod pck: .zip
Loaded mod pck: Island.zip
Initializing mod: Isle
Registered environment: Isle/Isle
Registered vehicle: Catcar
loaded profile: First Sketch
loaded profile: Grace
loaded profile: Island
ERROR: Condition "!is_connected_to_host()" is true.
   at: set_no_delay (core/io/stream_peer_tcp.cpp:227)
Connected to server
```
Then MQTT reports that it is trying to connect but fails with unknown error

### :ballot_box_with_check: Definition of Done checklist
- [ ] Meaningful title and valuable description in pull request
- [ ] Code change tested manually if not covered by automated tests
- [ ] Pull request linked to one or more issues/stories
- [ ] Acceptance criteria of the linked stories satisfied
- [ ] Code change comprehended by those who approved it
- [ ] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Dreia** [comment]
I forgot to mention that our MQTT connection between the app and the emulator does work.

**Comment by RuthgerD** [comment]
Where did this mqtt library come from? I strongly suggest using a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for this instead as vendoring library code is quite a bad practice without a good reason.

**Comment by RuthgerD** [comment]
> Good to know! I got it from [here](https://github.com/DynamicDevices/godot-multi/tree/master/godot-multi/addons/mqtt). It is meant to be an add-on and since you said no add-ons I tried to implement as a gdscript.

Okay considering that its _okay_ but be sure to clean it up before merging (e.g. the `tool` is not something you want) and adding a link below the copyright to the original source

**Comment by Dreia** [comment]
> > Good to know! I got it from [here](https://github.com/DynamicDevices/godot-multi/tree/master/godot-multi/addons/mqtt). It is meant to be an add-on and since you said no add-ons I tried to implement as a gdscript.
> 
> Okay considering that its _okay_ but be sure to clean it up before merging (e.g. the `tool` is not something you want) and adding a link below the copyright to the original source

Sure. I'll do that. Do you think this approach could work or is it very off ? I call the $mqtt.connect_to_server() inside the init_cam_position()

**Comment by RuthgerD** [comment]
Doing it this way is _a way_ as you can argue that since it works via mqtt it can easily be replaced with "real" hardware that detects the vehicle going over the finish. 

However, as of the current release of smce i believe you have all the tools necessary to create such a device which detects things going over the finish line:
- custom vehicle, could literally be a cube with a infrared sensor on it
- per vehicle label (see below)
- custom spawn location based on label hint 

So what you can do is make a custom vehicle, give it a distinct label and then have the environment spawn this vehicle right at the finish line.

This way you can write a sketch that does mqtt and benefit from the working mqtt implementation and of course provide more real world value.

If you have questions about doing it as described above ask in the help-technical channel about spawn labels :)

**Comment by Dreia** [comment]
Thanks. I know more or less how to do that.  I get the feeling that the kind of features that we have in mind for this sprint may not be exactly real world value though. Car can jump doesn't have much application outside of the world of games. Should we think of our features as modules that can be taken separately and implemented in other projects ?

**Comment by RuthgerD** [comment]
>  I get the feeling that the kind of features that we have in mind for this sprint may not be exactly real world value though.

This is why you hire marketing people to make it look like it has value :+1:

**Pull request closed without merging**
