### PR TITLE
Fixed the speedometer bug while using the Reset button

### PR DESCRIPTION
**Pull request by Quinstedt**
The bug with the speedometer has been fixed while doing so I noticed that the joystick was actually missing the backend for the reset button. 

Closes related issue: #86 
This request is related to the following issues:
#6 
#55 
#62 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by faisal1201** [comment]
Can you elaborate more on what the bug was with the speedometer so that I can test whether it is fixed ? Guessing from the changes in code, I think when the reset button is clicked , the speedometer needle didn't point back to 0m/s but i am not sure.

**Comment by Quinstedt** [comment]
if you are in speed 100 and you press reset the UI didnt when down to zero so when you tried to accelerade again you couldnt see the setup speed in the speedometer UI because the maximun was already at 100.

**Comment by Quinstedt** [comment]
The test still passing manually with Nexus 6 but not in the CI. 
image

**Review by faisal1201 — COMMENTED** [review]
The bug has been fixed . The speedometer goes back to 0 after clicking on reset. But, I found another bug. After I went to full speed and clicked on reset. The speedometer went back to 0 but then clicking on the Accelerate button didn't increase the speed by 10 m/s and clicking the brake button sets the speed to 90 .

**Comment by Quinstedt** [comment]
The bug is fixed. When I drive and use the reset button the UI goes to 0. Then if I press accelarate it goes up to 10 again.  The status of everyghing is also reser to the begining setttings. 

I have also added that the car stops when you press the escape hash.

**Review by faisal1201 — APPROVED** [review]
The Issues identified are all fixed now.

**Review by faisal1201 — APPROVED** [review]

**Pull request merged**
