### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by faisal1201**
Models to show Mosquitto broker connections between different system components.

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Review by Quinstedt — CHANGES_REQUESTED** [review]
I think we could just use 1 arrow instead of two. I dont think we need to show that the broker publish to the broker. Basically is the app listing to the broker and when a message that matches a subscribe topic the the app takes that information from the broker. 

For example:  Godot publish the topic ("/IslandRush/Mood/Race/Finish")
Godot ---publises---> Broker
But The app subscribes that message. 
App <----subscribes ---  Godot  ( the topic)

**Comment by faisal1201** [comment]
@Quinstedt  it's fixed now

**Review by Quinstedt — COMMENTED** [review]
Hi, sorry I have a little more to add. 
The app is the direction topic  and Arduino is subcribing it . 
"/IslandRush/Control/Direction"
"/IslandRush/Control/Speed"; (commin real soon)
We also have the arduino sending:
The (1) actual speed of the car, (2) the distance of the car and the (3) camera to the app 
 
 We could also create a more generic diagram showing which ones are subscribing and publishing or both. And create a table to for the topics. But both works of course. 
 Otherwise it looks good =) great job

**Comment by faisal1201** [comment]
Hello, as you mentioned the app is publishing the direction and speed topics and the arduino subscribes to both of them by using this topic "/IslandRush/Control/#". I think the "#"  is a wildcard which means that it subscribes to both "/IslandRush/Control/Direction" and "/IslandRush/Control/Speed" topics. I also have shown that the arduino is sending the speed,distance and camera of the car.
But, i think your idea of having a generic diagram to include publishes or subscribe and then including a table for the publish and sublish topics would be better. And might lessen confusion.I can work on it and update the readme accordingly.

**Comment by faisal1201** [comment]
I have updated the Readme.md once more . Ready for more feedback!

**Comment by Quinstedt** [comment]
Great job @faisal1201 the wiki looks good

**Pull request merged**
