### PR TITLE
Connecting the components for the finish of the race

### PR DESCRIPTION
**Pull request by Quinstedt**
The timer, the animation for the leaderboard and the controllers have been added. 
Solved the issue left in #55 : 
The finish line textview has now been added to all the related activities. (it was in only 1 out of 4)
Solved the redundance of the code and moved the finish time text view so that it is connected to the leaderboard. 

Solved the issue left in #43 :
The connection has been added to the broker and the related activities. 
Changed the rankMessage textview to a RaceMessage view. 
Emojis have been added to the text in the leaderboard. 

A singleton class called Global has been added, it is an static class that can store information across the different classes in the application. Is use to store the name of the player and the time of the race. Its need to be connected to the database. 
Commentes in the class have been added. 

Utils class has been created for the emojis and a delay method which at the moment is not been used. Comments have been added. 

A constraint in Mainactivity not allowing an empty player name. A toastMessage has been created there and emojis have been added to the toastMessages. 

Closes related issue #69 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by Quinstedt** [comment]
The leaderboard animation when reaching the finish line

image

**Comment by Quinstedt** [comment]
the failing test is passing now manually
image

**Comment by Quinstedt** [comment]
the manual test is also passing now after adding the emoji
image

**Review by faisal1201 — APPROVED** [review]
Code change comprehended and redundant code is removed. All criteria from the pull request description is implemented. The only thing left is to insert the data to the database for processing and show it on the leaderboard, which will be done on the Database branch after pulling from master with these latest changes

**Comment by faisal1201** [comment]
Before I merge, i'll have a look why the instrumental test for the android CI is failing on push

**Review by faisal1201 — APPROVED** [review]

**Comment by Quinstedt** [comment]
I was just testing so the difference between connecting the issue from the sidebar and using # in the description

**Pull request merged**
