### PR TITLE
How to play Instructions and button Animation

### LINKED ISSUE #40: Instruction Screen
As a player, I want to know how to play the game before starting the game so that I am not lost while playing the game.
Acceptance Criteria:
i) How to start the game
ii) How to control the car instruction
iii) Objective of the game 
iv) Check your rank instruction

### PR DESCRIPTION
**Pull request by faisal1201**
This pull request has commits related to instructions of the game. A user will be able to go through this and become familiar with what the game offers and how the controls work. So, that the player isn't lost while playing the game.
Animations for buttons also added
Recommended device to test : Pixel 3 XL  API 31

Related Issue: closes  #40  #89 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Review by Quinstedt — CHANGES_REQUESTED** [review]
Good job, But Could maybe change the color to white. 
image

Black is a bit hard to read sometimes.

**Comment by faisal1201** [comment]
Yes , I can change the color to  white. Besides, what emulator are you using ? Seems like the whole layout can't be seen

**Comment by faisal1201** [comment]
The text layout has been changed to white so that it appears more visible to the user.

**Comment by faisal1201** [comment]
image

**Comment by Quinstedt** [comment]
I fixing the constraint in all the activities. So wait until my next message to merge

**Comment by Dreia** [comment]
IslandRush can be played in two modes...
That's what I would put. Otherwise it's user is incorrect, should be its user

**Comment by faisal1201** [comment]
The title can be changed np.

**Comment by Quinstedt** [comment]
The test are not passing because the title are not visible in the layout. Any particular reason why the recycle view is on top of the titles?

**Review by Quinstedt — APPROVED** [review]
This has been changes

**Comment by faisal1201** [comment]
What I have noticed is that the layout I made was for Pixel 3 XL API 31 and using another device which has a larger or smaller screen size changes the layout . Like the example you gave before, the recycle view is over the title.

**Comment by Quinstedt** [comment]
> What I have noticed is that the layout I made was for Pixel 3 XL API 31 and using another device which has a larger or smaller screen size changes the layout . Like the example you gave before, the recycle view is over the title.

ok, I fixed the constrait so everything is passing now.

**Comment by Quinstedt** [comment]
image
all test passing manually

**Review by Quinstedt — APPROVED** [review]
Everything in this branch is ready to be merge, test are passing, contrainsts have been improve for most of the layouts.

**Pull request merged**
