### PR TITLE
Removing .import folder and adding it to .gitignore

### PR DESCRIPTION
**Pull request by Quinstedt**
Removing the .import folder from the respository and .import has been add to .gitignore.
To avoid adding bloat to future revisions. 

Closes related issue: #49 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Quinstedt** [comment]
@RuthgerD please leave here a review or a just message so that we can proceed with the merge of this branch. 
Thank you for your help with this and thank you for creating this issue.

**Review by RuthgerD — APPROVED** [review]

**Comment by AeroStun** [comment]
(This might not fix the slowdown because your Git history is now tainted)

**Comment by Quinstedt** [comment]
> (This might not fix the slowdown because your Git history is now tainted)
oh I see, is it possible to fix the slowdown ?

**Comment by Quinstedt** [comment]
@faisal1201 can you do the checks for the DoD to this.

**Comment by AeroStun** [comment]
> oh I see, is it possible to fix the slowdown ?

Purge the repo of that file. You can take a page from the GitHub Security handbook
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

**Review by faisal1201 — APPROVED** [review]
No .import folder found in the Mod Directory when this branch was pushed . This issue is fixed .

**Pull request merged**
