### PR TITLE
mod as artifact CI

### PR DESCRIPTION
**Pull request by Dreia**
I tried to make a workflow for the mod. I'm trying to produce a downloadable Island.zip file from the Mod directory. I am not sure if this is what you had in mind for this CI. Can we do this even though we gitignored the .import files?

Fixes related issue #61  

### :ballot_box_with_check: Definition of Done checklist
- [ ] Meaningful title and valuable description in pull request
- [ ] Code change tested manually if not covered by automated tests
- [ ] Pull request linked to one or more issues/stories
- [ ] Acceptance criteria of the linked stories satisfied
- [ ] Code change comprehended by those who approved it
- [ ] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by platisd** [comment]
Well, to begin with the workflow has to be a `yaml` file.
Secondly, I guess you need to generate some files, then upload them and make them part of some release?
@RuthgerD may know more and probably he's the one you have discussed this with.

**Comment by AeroStun** [comment]
See https://github.com/godotengine/godot-proposals/issues/1362

**Comment by Dreia** [comment]
> See [godotengine/godot-proposals#1362](https://github.com/godotengine/godot-proposals/issues/1362)

It looks like a controversial issue, maybe there is some other workflow that we can have for the mod that is more safe ?

**Comment by AeroStun** [comment]
That's not a workflow. There's just useful info in the comments in there to possibly regenerate your imports on CI.
There are plenty of Godot export workflows floating around the marketplace, but I suspect they all require a pre-imported project.

**Comment by Dreia** [comment]
> That's not a workflow. There's just useful info in the comments in there to possibly regenerate your imports on CI.
> There are plenty of Godot export workflows floating around the marketplace, but I suspect they all require a pre-imported project.

I see, not planning to upload the whole project to the repo. But I could zip the file on my computer and make the .zip file an artifact that can be downloaded separately. That could be useful.

**Comment by AeroStun** [comment]
> I see, not planning to upload the whole project to the repo.
Sounds closed source to me 😢

**Comment by Dreia** [comment]
> > I see, not planning to upload the whole project to the repo.
> 
> Sounds closed source to me 😢

Well sounds like ItJustDoesn'tWork to me, people complain about it in the link you sent. But I'll try. Thanks.

**Comment by RuthgerD** [comment]
What you can do is call `godot --export-pack {preset} {output}` on your ci; only a linux runner is needed and it _should_ regenerate the resource files before export.

**Comment by platisd** [comment]
> What you can do is call `godot --export-pack {preset} {output}` on your ci; only a linux runner is needed and it _should_ regenerate the resource files before export.
> 
> Zipping the project folder only works when the editor did that job already so it won't work here (:

That however means that they will be building their mod on CI, which is great, but may not be necessarily as trivial as they expected, right?

**Comment by RuthgerD** [comment]
> but may not be necessarily as trivial as they expected

There are [godot docker images](https://github.com/abarichello/godot-ci) available on the internet, and otherwise smce-gd [downloads](https://github.com/ItJustWorksTM/smce-gd/blob/master/.github/workflows/ci.yaml#L80) [godot](https://github.com/ItJustWorksTM/smce-gd/blob/master/.github/workflows/ci.yaml#L106) from the binary release and sets it up on the PATH.

If this is considered hard or trivial is up to the reader.

**Comment by RuthgerD** [comment]
Also actually..  if you have a recent version of godot you can just hack it by doing:
```
timeout 10s godot . --editor --no-window
```
which hopefully opens the editor to generate the resources, then closes after 10 seconds (after which you can use the zip method), open question is if that still needs opengl drivers :P

**Comment by Dreia** [comment]
@RuthgerD , @AeroStun I have followed your instructions and came up with this. It doesn't look like there is any way to check if it works before merging though. Should I upload it to the branch it is supposed to work on and make another pull request ?

**Comment by AeroStun** [comment]
Well it sure won't work because the file is misplaced

**Comment by AeroStun** [comment]
Once the workflow is placed at the right location, it should be triggered already, so you'll get to see if it does what you intend

**Comment by Dreia** [comment]
Thanks, I was not sure. I will move to the other branch then and close this pull request

**Pull request closed without merging**
