### PR TITLE
Joystick backend and stop button. Including display improvements

### PR DESCRIPTION
**Pull request by Quinstedt**
Joystick backend has been implemmented with the requered 8 direction and a stop button. The Arduino file has been updated and fixed a bug in the directions of the joystick. The connection of the joystick to the MQtt broker has been succesfully implemented. Extra things done: 
- Both the controlPad and the Joystick are now also displaying the actual speed of the car in m/s.
- The camera filter has been updated to improve the video stream from the car. 
- Comments on important methods inside Joystick, ControlPad and BrokerConnection
Closes related issue: #22 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Quinstedt** [comment]
There are repeated push with the same name, because I tried to use the Android app git without success but when I pushed from GitBash apperantly all of them appeared here, which I didnt knew it will happen.

**Review by Dreia — DISMISSED** [review]
Good work!

**Comment by faisal1201** [comment]
Same here. The DOD criteria doesn't appear. We can't merge it until all the criteria is marked and the DOD CI check passes

**Comment by Quinstedt** [comment]
I just added it now

**Review by faisal1201 — COMMENTED** [review]
When I executed the app with broker on, it gave me "Failed to connect to broker"  error upon choosing the control type.

**Comment by Quinstedt** [comment]
I have inserted a comment on where to test the GODOT and APP in BrokerConnection with instruction on how it works

**Review by faisal1201 — APPROVED** [review]
Acceptance Criteria for Joystick-Backend fulfilled.
Connection Issue to the broker was fixed. Controlling the car was smooth and without lag.

**Comment by Quinstedt** [comment]
The comments have been pushed in #50

**Comment by Quinstedt** [comment]
#79 was added by misstake. The only issues related are the one in the description.

**Pull request merged**
