### PR TITLE
Splash animation and app icon 

### LINKED ISSUE #29: App Intro Animation
As a player I would like to have an intro animation before the game starts in order to know what the game is about.
Acceptance criteria:
- The animation starts within a second from opening the app. 
- The animation is related to the game name and strategy.
- The animation lasts at least 5 seconds.
- The animation doesn't have noticeable lags longer than 0.001 seconds.

### PR DESCRIPTION
**Pull request by safayoussef**
Animation splash for the start of the app. 
The app icon has been change to our Logo. 

<del>Note that to have the splash in the starting of the app, we needed to create a new activity and class for the previous MainActivity now call MainPage. 

<del>And the Splash animation is in the MainActivity class and layout. 

Related issue: Closes #29  

CoAuthor: @Quinstedt :  The merge of the splash activity with the android project.  

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by Quinstedt** [comment]
There is a better solution for the Splash Animation instead of restructure the layouts and the classes and creating MainPage.
 Change the manifest from this: 
 
image
To this:
image

**Review by faisal1201 — COMMENTED** [review]
Also is it possible  to have the car get back to the starting position after the animation ends. Instead of having it on the top of the tree. I was thinking it would look nicer if the car  gets back to the original position after  it passes through the screen.

**Comment by faisal1201** [comment]
It might be an issue with android studio but the animation still works and manifest has been changed. We can merge now.

**Review by faisal1201 — APPROVED** [review]
The animation is working once executed and changes to the home screen afterwards.

**Comment by safayoussef** [comment]
> 



> Also is it possible to have the car get back to the starting position after the animation ends. Instead of having it on the top of the tree. I was thinking it would look nicer if the car gets back to the original position after it passes through the screen.

it is not possible

**Pull request merged**
