### PR TITLE
Modified car

### PR DESCRIPTION
**Pull request by restless-learner**
The newest modification of our race car having the unnecessary sensors (the whole set of infrareds, ultrasonic and camera) revoked with adjusted vehicle_config JSON file.
tropical car

Instructions for testing here [here](https://github.com/DIT113-V22/group-08/wiki/Modding-Instructions)

### :ballot_box_with_check: Definition of Done checklist
- [ ] Meaningful title and valuable description in pull request
- [ ] Code change tested manually if not covered by automated tests
- [ ] Pull request linked to one or more issues/stories
- [ ] Acceptance criteria of the linked stories satisfied
- [ ] Code change comprehended by those who approved it
- [ ] State of target branch maintained or improved after the code change
- [ ] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by Quinstedt** [comment]
I cannot start the car I get this error
image

**Review by faisal1201 — CHANGES_REQUESTED** [review]
image
I am receiving  the same errors as Nicole.
Also, the linked issue states to create a modified car for the Finish Line detection and not the racing car.

**Comment by restless-learner** [comment]
@Quinstedt @faisal1201 I want to figure out how you run it. I have just downloaded the zip of the branch car-modding, opened it via Godot engine, exported the project as a zip into the C:\Users\username\AppData\Roaming\Godot\app_userdata\SMCE\mods folder and after this ran the SMCE Godot emulator and the car downloaded well. Did you do it in this way?

**Comment by restless-learner** [comment]
Just make sure you are running a sketch from car-modding branch as well since the json config file is changed and you cannot run the sketch from master or whichever branch

**Comment by Quinstedt** [comment]
Can it be because we are using the latest mod?
Im using the car from your branch but the latest mod from andrea

**Comment by faisal1201** [comment]
@restless-learner  I had the Island.zip file from master inside the mod directory. Then, changed the environment in SMCE to it and tried to open the sketch from car-modding branch but then it gave me that error.

**Comment by Dreia** [comment]
@restless-learner, I guess you could make a version that we could test by downloading the mod from Exploration and Race branch and adding the car as a new folder inside vehicles with different name, then modify Island.gd as well to also register your vehicle. Then, in playground.gd copy line 12 and replace catcar with your car name. The name needs to be the one from the vehicle.json. 
After these modifications you can just push to this branch and the Island.zip file will be exported by the CI. You can paste the link to the workflow that was ran after you pushed and this way we get your version of the .zip.
The sooner we merge the better

**Review by Dreia — CHANGES_REQUESTED** [review]
@restless-learner, I guess you could make a version that we could test by downloading the mod from Exploration and Race branch and adding the car as a new folder inside vehicles with different name, then modify Island.gd as well to also register your vehicle. Then, in playground.gd copy line 12 and replace catcar with your car name. The name needs to be the one from the vehicle.json.
After these modifications you can just push to this branch and the Island.zip file will be exported by the CI. You can paste the link to the workflow that was ran after you pushed and this way we get your version of the .zip.
The sooner we merge the better

**Comment by Quinstedt** [comment]
This pull request will be left open. @restless-learner  will not finish the project with us. 
image

**Comment by restless-learner** [comment]
I just close it and will probably open and work on it during the resubmission.

**Pull request closed without merging**
