### PR TITLE
Animation for the ending of game

### PR DESCRIPTION
**Pull request by itsdanesh**
added the animation to show up when the game is finnished. It will show player's name, ranking, and a short message. 

Closes the related issue: #68 

### :ballot_box_with_check: Definition of Done checklist
- [x] Meaningful title and valuable description in pull request
- [x] Code change tested manually if not covered by automated tests
- [x] Pull request linked to one or more issues/stories
- [x] Acceptance criteria of the linked stories satisfied
- [x] Code change comprehended by those who approved it
- [x] State of target branch maintained or improved after the code change
- [x] Go to MainActivityTest in the Android App and uncommit @Test <br> Run test manually. Add a picture of the test result in the comments. <br> Comment @Test again to avoid future problems with the CI

### CODE REVIEW

**Comment by itsdanesh** [comment]
mainActivityTest

the result of MainActivityTest

**Comment by Quinstedt** [comment]
image

dont use the same issue that in the picture

**Comment by Quinstedt** [comment]
just add that in the description. 
Closes related issue # ...

**Comment by Quinstedt** [comment]
it is ok now.

image

**Comment by Quinstedt** [comment]
image

Passing the test

**Review by Quinstedt — APPROVED** [review]
The animation is working.  In issue #69 the leaderboard will be connected  so that it appears at the end of the race. It will also be connected to the leaderboard data in #3 .

**Pull request merged**
